# Generated by Django 4.2.8 on 2023-12-18 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_email_token_profile_otp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='is_email_verified',
            new_name='is_otp_verified',
        ),
    ]
